"""Deterministic identity for the code-defined MLB predictive model surface.

MLB's active production candidates are generated by code-defined simulation
engines rather than one fitted coefficient blob.  This module gives that real
predictive surface an immutable artifact identity by binding the exact Git blob
bytes of every authoritative engine module.  The artifact is provenance only:
it never changes deployment eligibility, calibration, evidence, or Truth Gate.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Mapping

SCHEMA_VERSION = "MLB_CODE_MODEL_ARTIFACT_V1"
DEFAULT_MANIFEST = Path("config/mlb_model_surface_v1.json")


class MLBModelArtifactError(ValueError):
    pass


def _canonical_sha256(value: Mapping[str, Any]) -> str:
    raw = json.dumps(dict(value), sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def _git_blob_sha1(raw: bytes) -> str:
    header = f"blob {len(raw)}\0".encode("ascii")
    return hashlib.sha1(header + raw).hexdigest()


def load_verified_mlb_model_artifact(
    manifest_path: str | Path | None = None,
    *,
    repo_root: str | Path | None = None,
) -> dict[str, Any]:
    root = Path(repo_root).resolve() if repo_root is not None else Path(__file__).resolve().parents[1]
    target = Path(manifest_path) if manifest_path is not None else root / DEFAULT_MANIFEST
    if not target.is_absolute():
        target = root / target
    try:
        payload = json.loads(target.read_text(encoding="utf-8"))
    except Exception as exc:
        raise MLBModelArtifactError("MLB_MODEL_ARTIFACT_MANIFEST_UNREADABLE") from exc
    if not isinstance(payload, dict) or payload.get("schema_version") != SCHEMA_VERSION:
        raise MLBModelArtifactError("MLB_MODEL_ARTIFACT_SCHEMA_INVALID")
    if payload.get("artifact_kind") != "CODE_DEFINED_MODEL_SURFACE":
        raise MLBModelArtifactError("MLB_MODEL_ARTIFACT_KIND_INVALID")
    if payload.get("promotion_eligible_by_artifact_alone") is not False:
        raise MLBModelArtifactError("MLB_MODEL_ARTIFACT_PROMOTION_FLAG_INVALID")
    files = payload.get("files")
    if not isinstance(files, dict) or not files:
        raise MLBModelArtifactError("MLB_MODEL_ARTIFACT_FILES_REQUIRED")
    for rel, expected in sorted(files.items()):
        path = root / str(rel)
        expected_sha = str(expected or "").strip().lower()
        if len(expected_sha) != 40 or any(ch not in "0123456789abcdef" for ch in expected_sha):
            raise MLBModelArtifactError(f"MLB_MODEL_ARTIFACT_BLOB_SHA_INVALID:{rel}")
        try:
            actual = _git_blob_sha1(path.read_bytes())
        except OSError as exc:
            raise MLBModelArtifactError(f"MLB_MODEL_ARTIFACT_FILE_MISSING:{rel}") from exc
        if actual != expected_sha:
            raise MLBModelArtifactError(f"MLB_MODEL_ARTIFACT_SURFACE_MISMATCH:{rel}")
    return {
        "schema_version": SCHEMA_VERSION,
        "artifact_kind": payload["artifact_kind"],
        "model_artifact_sha256": _canonical_sha256(payload),
        "surface_files": tuple(sorted(files)),
        "promotion_eligible_by_artifact_alone": False,
    }


def mlb_model_artifact_sha256(**kwargs: Any) -> str:
    return str(load_verified_mlb_model_artifact(**kwargs)["model_artifact_sha256"])
