"""Structural Engine B participation/usage allocation over Engine A play paths.

Engine B assigns player identity to opportunities already generated by Engine A.
It does not create independent attempts, targets, receptions, carries, yards or
TD events. Unresolved participation fails closed.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

from .drive_play import FootballPlayPath, PlayEvent


@dataclass(frozen=True)
class PlayerUsageProfile:
    player_id: str
    team: str
    position: str
    active: bool | None
    snap_share: float
    route_participation: float
    target_share: float
    rush_share: float
    red_zone_share: float

    def __post_init__(self) -> None:
        if not str(self.player_id).strip():
            raise ValueError("PLAYER_ID_REQUIRED")
        if not str(self.team).strip():
            raise ValueError("PLAYER_TEAM_REQUIRED")
        if not str(self.position).strip():
            raise ValueError("PLAYER_POSITION_REQUIRED")
        if self.active is not None and not isinstance(self.active, bool):
            raise ValueError("PLAYER_ACTIVE_STATE_INVALID")
        for name in (
            "snap_share",
            "route_participation",
            "target_share",
            "rush_share",
            "red_zone_share",
        ):
            value = float(getattr(self, name))
            if not 0.0 <= value <= 1.0:
                raise ValueError(f"PLAYER_USAGE_SHARE_OUT_OF_RANGE:{name}")


@dataclass(frozen=True)
class TeamUsageProfile:
    team: str
    players: tuple[PlayerUsageProfile, ...]
    quarterback_id: str

    def __post_init__(self) -> None:
        if not str(self.team).strip():
            raise ValueError("TEAM_USAGE_TEAM_REQUIRED")
        if not self.players:
            raise ValueError("TEAM_USAGE_PLAYERS_REQUIRED")
        ids = [player.player_id for player in self.players]
        if len(ids) != len(set(ids)):
            raise ValueError("DUPLICATE_PLAYER_USAGE_ID")
        if any(player.team != self.team for player in self.players):
            raise ValueError("PLAYER_USAGE_TEAM_MISMATCH")
        matches = [player for player in self.players if player.player_id == self.quarterback_id]
        if len(matches) != 1:
            raise ValueError("TEAM_USAGE_QUARTERBACK_ID_INVALID")
        if matches[0].position.upper() != "QB":
            raise ValueError("TEAM_USAGE_QUARTERBACK_POSITION_INVALID")

    def player(self, player_id: str) -> PlayerUsageProfile:
        for player in self.players:
            if player.player_id == player_id:
                return player
        raise KeyError(player_id)


@dataclass(frozen=True)
class AttributedPlay:
    base_play: PlayEvent
    active_player_ids: tuple[str, ...]
    passer_id: str | None = None
    target_id: str | None = None
    receiver_id: str | None = None
    rusher_id: str | None = None
    touchdown_scorer_id: str | None = None
    allocation_fallback: bool = False

    def __post_init__(self) -> None:
        play_type = self.base_play.play_type.upper()
        active = set(self.active_player_ids)
        for player_id in (
            self.passer_id,
            self.target_id,
            self.receiver_id,
            self.rusher_id,
            self.touchdown_scorer_id,
        ):
            if player_id is not None and player_id not in active:
                raise ValueError("ATTRIBUTED_PLAYER_NOT_ACTIVE")

        if play_type == "PASS":
            if self.passer_id is None or self.target_id is None:
                raise ValueError("PASS_ATTRIBUTION_REQUIRED")
            if self.base_play.pass_complete is True and self.receiver_id != self.target_id:
                raise ValueError("COMPLETION_RECEIVER_TARGET_MISMATCH")
            if self.base_play.pass_complete is False and self.receiver_id is not None:
                raise ValueError("INCOMPLETE_PASS_HAS_RECEIVER")
            if self.rusher_id is not None:
                raise ValueError("PASS_CANNOT_HAVE_RUSHER")
            if self.base_play.points == 7 and self.touchdown_scorer_id != self.receiver_id:
                raise ValueError("PASS_TD_SCORER_MISMATCH")
        elif play_type == "RUSH":
            if self.rusher_id is None:
                raise ValueError("RUSH_ATTRIBUTION_REQUIRED")
            if any(value is not None for value in (self.passer_id, self.target_id, self.receiver_id)):
                raise ValueError("RUSH_CANNOT_HAVE_PASS_ATTRIBUTION")
            if self.base_play.points == 7 and self.touchdown_scorer_id != self.rusher_id:
                raise ValueError("RUSH_TD_SCORER_MISMATCH")
        else:
            if any(
                value is not None
                for value in (
                    self.passer_id,
                    self.target_id,
                    self.receiver_id,
                    self.rusher_id,
                    self.touchdown_scorer_id,
                )
            ):
                raise ValueError("NON_OFFENSIVE_PLAY_HAS_PLAYER_ATTRIBUTION")


def _blank_stats() -> dict[str, int]:
    return {
        "pass_attempts": 0,
        "completions": 0,
        "passing_yards": 0,
        "passing_tds": 0,
        "interceptions": 0,
        "rush_attempts": 0,
        "rushing_yards": 0,
        "targets": 0,
        "receptions": 0,
        "receiving_yards": 0,
        "rushing_tds": 0,
        "receiving_tds": 0,
        "touchdowns": 0,
        "longest_completion": 0,
        "longest_reception": 0,
        "longest_rush": 0,
        "pass_plus_rush_yards": 0,
        "rush_plus_receiving_yards": 0,
    }


@dataclass(frozen=True)
class AttributedFootballPath:
    base_path: FootballPlayPath
    home_usage: TeamUsageProfile
    away_usage: TeamUsageProfile
    plays: tuple[AttributedPlay, ...]

    def __post_init__(self) -> None:
        if self.home_usage.team != self.base_path.home_team:
            raise ValueError("HOME_USAGE_TEAM_MISMATCH")
        if self.away_usage.team != self.base_path.away_team:
            raise ValueError("AWAY_USAGE_TEAM_MISMATCH")
        if len(self.plays) != len(self.base_path.plays):
            raise ValueError("ATTRIBUTED_PLAY_COUNT_MISMATCH")
        for base, attributed in zip(self.base_path.plays, self.plays):
            if attributed.base_play != base:
                raise ValueError("ATTRIBUTED_BASE_PLAY_MISMATCH")

    def player_stats(self) -> dict[str, dict[str, int]]:
        stats: dict[str, dict[str, int]] = {
            player.player_id: _blank_stats()
            for profile in (self.home_usage, self.away_usage)
            for player in profile.players
        }

        for attributed in self.plays:
            play = attributed.base_play
            play_type = play.play_type.upper()
            if play_type == "PASS":
                assert attributed.passer_id is not None
                assert attributed.target_id is not None
                passer = stats[attributed.passer_id]
                target = stats[attributed.target_id]
                passer["pass_attempts"] += 1
                target["targets"] += 1
                if play.turnover_type == "INTERCEPTION":
                    passer["interceptions"] += 1
                if play.pass_complete:
                    assert attributed.receiver_id is not None
                    receiver = stats[attributed.receiver_id]
                    passer["completions"] += 1
                    passer["passing_yards"] += play.yards
                    passer["longest_completion"] = max(passer["longest_completion"], play.yards)
                    receiver["receptions"] += 1
                    receiver["receiving_yards"] += play.yards
                    receiver["longest_reception"] = max(receiver["longest_reception"], play.yards)
                    if play.points == 7:
                        passer["passing_tds"] += 1
                        receiver["receiving_tds"] += 1
                        receiver["touchdowns"] += 1
            elif play_type == "RUSH":
                assert attributed.rusher_id is not None
                rusher = stats[attributed.rusher_id]
                rusher["rush_attempts"] += 1
                rusher["rushing_yards"] += play.yards
                rusher["longest_rush"] = max(rusher["longest_rush"], play.yards)
                if play.points == 7:
                    rusher["rushing_tds"] += 1
                    rusher["touchdowns"] += 1

        for row in stats.values():
            row["pass_plus_rush_yards"] = row["passing_yards"] + row["rushing_yards"]
            row["rush_plus_receiving_yards"] = row["rushing_yards"] + row["receiving_yards"]
        return stats

    def assert_reconciliation(self) -> None:
        stats = self.player_stats()
        for usage in (self.home_usage, self.away_usage):
            team = usage.team
            ids = {player.player_id for player in usage.players}
            team_rows = [stats[player_id] for player_id in ids]
            plays = [play for play in self.base_path.plays if play.possession == team]
            pass_plays = [play for play in plays if play.play_type.upper() == "PASS"]
            rush_plays = [play for play in plays if play.play_type.upper() == "RUSH"]

            expected_attempts = len(pass_plays)
            expected_completions = sum(play.pass_complete is True for play in pass_plays)
            expected_pass_yards = sum(play.yards for play in pass_plays if play.pass_complete)
            expected_interceptions = sum(play.turnover_type == "INTERCEPTION" for play in pass_plays)
            expected_rush_attempts = len(rush_plays)
            expected_rush_yards = sum(play.yards for play in rush_plays)
            expected_offensive_tds = sum(
                play.points == 7 and play.play_type.upper() in {"PASS", "RUSH"}
                for play in plays
            )

            if sum(row["pass_attempts"] for row in team_rows) != expected_attempts:
                raise ValueError("QB_ATTEMPT_RECONCILIATION_FAILED")
            if sum(row["completions"] for row in team_rows) != expected_completions:
                raise ValueError("QB_COMPLETION_RECONCILIATION_FAILED")
            if sum(row["passing_yards"] for row in team_rows) != expected_pass_yards:
                raise ValueError("QB_PASS_YARDS_RECONCILIATION_FAILED")
            if sum(row["interceptions"] for row in team_rows) != expected_interceptions:
                raise ValueError("QB_INTERCEPTION_RECONCILIATION_FAILED")
            if sum(row["targets"] for row in team_rows) != expected_attempts:
                raise ValueError("TARGET_ATTEMPT_RECONCILIATION_FAILED")
            if sum(row["receptions"] for row in team_rows) != expected_completions:
                raise ValueError("RECEPTION_COMPLETION_RECONCILIATION_FAILED")
            if sum(row["receiving_yards"] for row in team_rows) != expected_pass_yards:
                raise ValueError("RECEIVING_PASS_YARDS_RECONCILIATION_FAILED")
            if sum(row["rush_attempts"] for row in team_rows) != expected_rush_attempts:
                raise ValueError("RUSH_ATTEMPT_RECONCILIATION_FAILED")
            if sum(row["rushing_yards"] for row in team_rows) != expected_rush_yards:
                raise ValueError("RUSH_YARDS_RECONCILIATION_FAILED")
            if sum(row["rushing_tds"] + row["receiving_tds"] for row in team_rows) != expected_offensive_tds:
                raise ValueError("OFFENSIVE_TD_RECONCILIATION_FAILED")
            if any(row["receptions"] > row["targets"] for row in team_rows):
                raise ValueError("RECEPTIONS_EXCEED_TARGETS")


class EngineBUsageAllocator:
    """Seeded player-identity allocator for one pair of team usage trees."""

    def __init__(
        self,
        home_usage: TeamUsageProfile,
        away_usage: TeamUsageProfile,
        *,
        seed: int | None = None,
    ) -> None:
        if seed is None:
            raise ValueError("EXPLICIT_SEED_REQUIRED")
        if isinstance(seed, bool) or not isinstance(seed, (int, np.integer)):
            raise ValueError("seed must be an integer")
        if not isinstance(home_usage, TeamUsageProfile) or not isinstance(away_usage, TeamUsageProfile):
            raise TypeError("TEAM_USAGE_PROFILE_REQUIRED")
        if home_usage.team == away_usage.team:
            raise ValueError("USAGE_HOME_AWAY_TEAM_COLLISION")
        self.home_usage = home_usage
        self.away_usage = away_usage
        self.seed = int(seed)
        self.rng = np.random.default_rng(self.seed)

    @staticmethod
    def _assert_resolved(usage: TeamUsageProfile) -> None:
        for player in usage.players:
            if player.active is None:
                raise ValueError(f"PARTICIPATION_UNRESOLVED:{player.player_id}")
        quarterback = usage.player(usage.quarterback_id)
        if quarterback.active is not True:
            raise ValueError(f"STARTING_QB_INACTIVE:{usage.quarterback_id}")

    def _active_set(self, usage: TeamUsageProfile) -> tuple[list[PlayerUsageProfile], bool]:
        active: list[PlayerUsageProfile] = []
        fallback = False
        for player in usage.players:
            if player.active is not True:
                continue
            if player.player_id == usage.quarterback_id or self.rng.random() < player.snap_share:
                active.append(player)
        quarterback = usage.player(usage.quarterback_id)
        if quarterback not in active:
            active.append(quarterback)
            fallback = True
        return active, fallback

    def _weighted_pick(
        self,
        players: list[PlayerUsageProfile],
        *,
        weight_name: str,
        red_zone: bool,
    ) -> PlayerUsageProfile:
        if not players:
            raise ValueError("USAGE_ALLOCATION_CANDIDATES_EMPTY")
        weights = []
        for player in players:
            weight = float(getattr(player, weight_name))
            if red_zone:
                weight *= max(0.05, player.red_zone_share)
            weights.append(max(0.0, weight))
        total = sum(weights)
        if total <= 0:
            raise ValueError(f"USAGE_ALLOCATION_WEIGHT_ZERO:{weight_name}")
        probabilities = np.array(weights, dtype=float) / total
        index = int(self.rng.choice(len(players), p=probabilities))
        return players[index]

    def _target(
        self,
        usage: TeamUsageProfile,
        active: list[PlayerUsageProfile],
        *,
        red_zone: bool,
    ) -> tuple[PlayerUsageProfile, bool]:
        route = [
            player
            for player in active
            if player.target_share > 0
            and player.player_id != usage.quarterback_id
            and self.rng.random() < player.route_participation
        ]
        fallback = False
        if not route:
            route = [
                player
                for player in usage.players
                if player.active is True
                and player.target_share > 0
                and player.player_id != usage.quarterback_id
            ]
            fallback = True
        if not route:
            raise ValueError("TARGET_ALLOCATION_UNAVAILABLE")
        return self._weighted_pick(route, weight_name="target_share", red_zone=red_zone), fallback

    def _rusher(
        self,
        usage: TeamUsageProfile,
        active: list[PlayerUsageProfile],
        *,
        red_zone: bool,
    ) -> tuple[PlayerUsageProfile, bool]:
        candidates = [player for player in active if player.rush_share > 0]
        fallback = False
        if not candidates:
            candidates = [player for player in usage.players if player.active is True and player.rush_share > 0]
            fallback = True
        if not candidates:
            raise ValueError("RUSH_ALLOCATION_UNAVAILABLE")
        return self._weighted_pick(candidates, weight_name="rush_share", red_zone=red_zone), fallback

    def attribute(self, path: FootballPlayPath) -> AttributedFootballPath:
        if not isinstance(path, FootballPlayPath):
            raise TypeError("FOOTBALL_PLAY_PATH_REQUIRED")
        if path.home_team != self.home_usage.team or path.away_team != self.away_usage.team:
            raise ValueError("USAGE_PATH_TEAM_MISMATCH")
        self._assert_resolved(self.home_usage)
        self._assert_resolved(self.away_usage)

        attributed: list[AttributedPlay] = []
        for play in path.plays:
            usage = self.home_usage if play.possession == path.home_team else self.away_usage
            active, fallback = self._active_set(usage)
            active_ids = {player.player_id for player in active}
            play_type = play.play_type.upper()
            passer_id: str | None = None
            target_id: str | None = None
            receiver_id: str | None = None
            rusher_id: str | None = None
            touchdown_scorer_id: str | None = None
            red_zone = play.yardline_100 <= 20 or play.points == 7

            if play_type == "PASS":
                passer_id = usage.quarterback_id
                target, target_fallback = self._target(usage, active, red_zone=red_zone)
                fallback = fallback or target_fallback
                target_id = target.player_id
                active_ids.add(target_id)
                if play.pass_complete:
                    receiver_id = target_id
                    if play.points == 7:
                        touchdown_scorer_id = target_id
            elif play_type == "RUSH":
                rusher, rush_fallback = self._rusher(usage, active, red_zone=red_zone)
                fallback = fallback or rush_fallback
                rusher_id = rusher.player_id
                active_ids.add(rusher_id)
                if play.points == 7:
                    touchdown_scorer_id = rusher_id

            attributed.append(
                AttributedPlay(
                    base_play=play,
                    active_player_ids=tuple(sorted(active_ids)),
                    passer_id=passer_id,
                    target_id=target_id,
                    receiver_id=receiver_id,
                    rusher_id=rusher_id,
                    touchdown_scorer_id=touchdown_scorer_id,
                    allocation_fallback=fallback,
                )
            )

        result = AttributedFootballPath(
            base_path=path,
            home_usage=self.home_usage,
            away_usage=self.away_usage,
            plays=tuple(attributed),
        )
        result.assert_reconciliation()
        return result

    def attribute_many(self, paths: list[FootballPlayPath]) -> list[AttributedFootballPath]:
        return [self.attribute(path) for path in paths]
